# Generated by Django 5.0.8 on 2024-08-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(to='airport.crew'),
        ),
    ]
