# Generated by Django 5.0.8 on 2024-08-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['seat'], 'verbose_name_plural': 'Tickets'},
        ),
    ]
