# Generated by Django 5.0.8 on 2024-08-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_remove_ticket_unique_flight_ticket_unique_flight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_flight',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'flight'), name='unique_flight'),
        ),
    ]
