# Generated by Django 5.0.8 on 2024-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_order_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['route', 'airplane'], name='airport_fli_route_i_6c5c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='airport_fli_departu_abe547_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['arrival_time'], name='airport_fli_arrival_a12903_idx'),
        ),
    ]
