# Generated by Django 5.0.8 on 2024-08-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_remove_ticket_unique_flight_ticket_unique_flight'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['source', 'destination'], name='airport_rou_source__5c8f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['distance'], name='airport_rou_distanc_e43817_idx'),
        ),
    ]
