# Generated by Django 5.0.8 on 2024-08-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_route_airport_rou_source__5c8f4c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_flight',
        ),
    ]
